server:
  port: 9093

#mybatis配置
mybatis:
  type-aliases-package: com.cykj.bean
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring配置
spring:
  application:
    name: SpringCloud-Provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.194.127:3306/oneStopService?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  mvc:
    static-path-pattern: /images/**
  resources:
    static-locations: classpath:/Provider/, classpath:/static/, classpath:/EmpFolder/, classpath:/file/
  redis:
    host: 127.0.0.1
    port: 6379


app:
  #appId
  appId: 2021000116673185
  #商户私钥
  privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCJzWPj4QY0Oec36Xr+rhGtWgvH5kRVHcS6TvD57G9HoXY1RlQFQ4Efvrhi65AHYM30vlD/rVUMATF/bwRrPRwwq7FsH/7jlGqjLBYu0vK0JQXaGfzxx9gdzQxzwJ9w9lHXSKAfJjlR5ijYuegyckHtS4vfXKuYr7YIrGOMCXf/j0uJBtvS6Z28uYR7BKbQhlSjSV8CfutuB2ldOyXjF7ESo/XFWt0kxp2lFtcWG13ptfZ8t0fxucMxRLqLvpc4MveXrJ7MnmVoxgVPh/mOqea9LyW7+jfjrcPYgOQ+k5ed+b8PIGE+T1QCia0/uhoTQRQ/fdr8JEPK562WIMnEcmvxAgMBAAECggEANCIqOlo1mKiXW0XPrG56bZT1hAkPrQv4E2wuKr9SUk05hWo3+03QmgvzgikQclojUQZ3amNPG52P9mAv0cpq0dcC5p8sNTk/JsBVHB3eiFzBXAQc9/PdRVj/7wLez0PBLqthOKejY+KpbWTX/c3QN1AveK98k+VV/u4JMz+Z0Gr9yV61OcZCx+lOv+SoO+hssLE3Cygq4TjTscJe51yU3cNpnCMkDX8+QB1WLZO7HZRH0nlZeReAr2XLlSvbWub2m9ue7REpFkDQjmbYzSM8aAy2WqG/IlJomepsMItMV2ZexfNQbxvVIQzKuXnRv6YQwhKgVqZiAV8hdPbWUOlYgQKBgQC/rEllW0HD0tIKs4GTy0Vl/2sNatLhWsS0uYN1Nmwme8gQvK/wcKpLNk5aj83KEUfQr0XvAzc4nsd4Q/2WMCYCgqi1fNnbAXv2HJhJlByu3QCspom9g9vZkbzY1YeRfzL2M0+x6OgOtKrdmBeXTaFzHTxytBFMEcQiJLAZAs8eqQKBgQC4DMRqbGLP4D0wC78Kgb8jyDa0QUzx67079DYP77n5NWhyM/abAURS71r0eNHFzicYvmsCIm9cDwvL/HgfytcbVp5TPWNhS4lX/7WbVCb76j9MdyzvDAa/1kYZIflzRQ32wrltyR/HBPSZcgV5cY8Fwras44qrfEAdr8Jj0QaYCQKBgFx3QPEklRVjHvEKp/gkl9Yc4ggXAKS2pS6KUGC7YHEwRdPNMxNLRtwB1srZlO1maL7Dz3j+lCU8c/4QzsUldTDA16K2GGMO1D5mjRDx4uR4uVqQ/OHwOp87L19ro3sNYghjuI6bTVfK0KMWPEtBqCFgeUjclXudFoFiMZHfSQwBAoGAPZ+QuC1YHE/xTL/yFBuDGwDzSAFBORL8RjGrVESo2QcH1I0PebC/5qDbrFUzr24p6v/+pjVPYdxrz73Vnpd01GN5GVfJiY8YCk3EyaAweVJiJUEV22gEboDY8ZtNgUnSthdWrKqVqDZBi4sAyDu8bmpWbaa2DFrKwOXTSUZ4VbkCgYBvnnts8DHEikhfW2qi17lhIKD7PSA7FNZJUaepXf/Q2H93jSkukp7lv8pau++XT/PTPB9IidrZf3iEor5QzgpcawRvVYJw7nsjBhIlAQxf1sXFzD7hYV/bba6MIFZWlGPyPRozzIGlWA/CkDqdU7TS/2yEDj9k/oL/VlfNqIhweA==
  #支付宝公钥
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmpdtdgdvrupWCr0Hhy/qHXG8nZNQgVA/8kQ/8X3xcTD0LOgNlsm23RKxg1K04GnEwCpFHJlAAoFtuFl3JhiH7rBSYroDH1T/qoJmRGOZlYFSEbJSkXYrgJZ1+tmbHcI1bpg0OTPjL3dEapNsGYd6XSghxsKaqDDjo9y8Btx+HA0lJrYOuyXI9mHbKX+0wd67g7FGLThYcRGkDb5m1gVPNIndyNQmnY1NtHcHTVXVmW2nDUzaHH26iArW22QxT/6dgc+o74MiuTitphfNlI0GMRA2YvET5BcVrKjQPqq0tSCfSSLri95LhsJVC1kxc8sFRWSus9MZutT1aYTSYeBioQIDAQAB
  #服务器异步通知页面路径，需要公网能访问到
  notifyUrl: http://localhost:9093/app/successa
  #服务器同步通知页面路径，需要公网能访问到
  returnUrl: http://localhost:9093/app/success
  signType: RSA2
  #字符编码格式
  charset: utf-8
  #支付宝网关
  gatewayUrl: https://openapi.alipaydev.com/gateway.do


