server:
  port: 9093

#mybatis配置
mybatis:
  type-aliases-package: com.cykj.bean
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


#spring配置
spring:
  application:
    name: SpringCloud-Provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #数据源
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.194.127:3306/oneStopService?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
